name: btc_miner_fun
description: "Mineur Bitcoin reel et pedagogique - Android + Windows"
publish_to: 'none'
version: 0.30.0+30

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  wakelock_plus: ^1.2.5
  qr_flutter: ^4.1.0
  ffi: ^2.1.0
  blockchain_utils: 7.1.0
  flutter_secure_storage: 11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <7.0.0"
  flutter_launcher_icons: ">=0.13.0 <1.0.0"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#080A10"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
